config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    resources :users, only: %i[show edit]
    get '/users/:id/chatrooms', to: 'users#chatrooms', as: :user_chatrooms
  end

  root to: 'pages#home'

  get '/search', to: 'pages#search'
  get '/dashboard', to: 'pages#dashboard'

  resources :categories, only: %i[new create index show]
  resources :activities, only: %i[new create show]
  resources :storages, only: %i[show new create edit update]
  resources :items, only: %i[index new create]
  resources :item_storages, only: %i[new create edit update destroy]
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: :create
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar" id="home">
  <%= link_to root_path do %>
    <%= image_tag "home-icon.svg"  %>
  <% end %>
  <%= link_to search_path do %>
    <%= image_tag "search-icon.svg", class: "navbar-icon"  %>
  <% end %>
  <%= link_to categories_path do %>
    <%= image_tag "explore-icon.svg", class: "navbar-icon-center" %>
  <% end %>

  <% if user_signed_in? %>
    <div id="notification-holder" data-user-id=<%= current_user.id%>>
      <%= link_to user_chatrooms_path(current_user) do %>
        <%= image_tag "msgs-icon.svg", class: "navbar-icon", id: "msg-icon" %>
        <%= image_tag "icon_message_active.svg", class: "navbar-icon d-none", id: "active-msg-icon" %>
      <% end %>
    </div>
    <%= link_to dashboard_path do %>
      <%= image_tag "profile-icon.svg"  %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
      <%= image_tag "msgs-icon.svg", class: "navbar-icon" %>
    <% end %>
    <%= link_to new_user_session_path do %>
      <%= image_tag "profile-icon.svg"  %>
    <% end %>
  <% end %>
</div>

app/views/shared/_search_bar.html.erb
<div class="form-container">
      <%= form_tag search_path, method: :get do %>
      <div id="search-data" data-items="<%=@items%>">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        placeholder: "Search here" %>
      </div>
      <% end %>
  </div>