config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    resources :users, only: %i[show edit]
    get '/users/:id/chatrooms', to: 'users#chatrooms', as: :user_chatrooms
  end

  root to: 'pages#home'

  get '/search', to: 'pages#search'
  get '/dashboard', to: 'pages#dashboard'

  resources :categories, only: %i[new create index show]
  resources :activities, only: %i[new create show]
  resources :storages, only: %i[show new create edit update]
  resources :items, only: %i[index new create]
  resources :item_storages, only: %i[new create edit update destroy]
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: :create
  end
end

app/views/pages/_info_window.html.erb
<p style="color: black; font-size: 18px"><%= belonging[0].username %></p>

<div class="d-flex">
  <% unless belonging[1].empty? %>
    <% belonging[1].each do |item| %>
      <%= cl_image_tag item.item.photo.key, class: "map-img" %>
    <% end %>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mt-3">
    <div class="user-info">
      <h2><%= @user.username %></h2>
      <small>Dashboard</small>
    </div>
    <%= cl_image_tag @user.photo.key, class: "user-img" %>
  </div>

  <div class="d-flex flex-column mt-4">

    <%= image_tag("save-the-planet.svg") %>

    <%= link_to edit_user_registration_path(current_user) do %>
    <div class="btn button-link-white mt-3">
      <small>Edit profile</small>
      <%= image_tag "arrow.svg", class: "icon"  %>
    </div>
    <% end %>

    <% if current_user.storage == nil  %>
      <%= link_to new_storage_path(current_user.storage) do %>
        <div class="btn button-link-white mt-3">
          <small>Create storage room</small>
          <%= image_tag "arrow.svg", class: "icon"  %>
        </div>
      <% end %>
    <% else  %>
      <%= link_to edit_storage_path(current_user.storage) do %>
        <div class="btn button-link-white mt-3">
          <small>Edit storage room</small>
          <%= image_tag "arrow.svg", class: "icon"  %>
        </div>
      <% end %>
    <% end %>

  </div>


</div>

app/views/pages/home.html.erb
<div class="on-mobile"><h1>Watch it on your mobile please!</h1></div>

<div class="login p-4 text-right">
  <% if user_signed_in? %>
    <%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "LOG IN", user_session_path %>
  <% end  %>
</div>

<div class="container d-flex flex-column">

  <section class="intro-container">
    <div class="logo">
      <h1>Planet Exchange</h1>
      <small>Borrow what you need</small>
    </div>

    <div class="start">
      <small>Get started</small>
      <%= image_tag("arrow-white.svg") %>
    </div>

    <div class="video-intro">
      <%= video_tag "video-intro.mp4", "video-intro.webm", "video-intro.ogv", id: "videoBG", autoplay: true, muted: true, controls: false, loop: true, playsinline: true %>
    </div>

  </section>
</div>
<div class="d-flex flex-column">

  <section class="onboarding-container" id="onboarding">
    <small class="text-center">how does it work?</small>

    <div class="swiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide px-4 pb-4">
          <%= image_tag("explore.svg") %>
          <h2>Explore</h2>
          <p class="text-left">Meet people around you and help each other out.
            Borrow an object in exchange for another, meet over a drink, make friends and more!</p>
        </div>

        <div class="swiper-slide pr-4 pl-4">
          <%= image_tag("store-room.svg") %>
          <h2>Store</h2>
          <p class="text-left">Create your own virtual storage room to help other users around you get started with their business.
            Let them know what you have available.</p>
        </div>

        <div class="swiper-slide pr-4 pl-4">
          <%= image_tag("save-the-planet.svg") %>
          <h2>Save</h2>
          <p class="text-left">Calculate and reduce your carbon footprint by exchanging items instead of buying them.
          Save the planet and make friends!</p>
        </div>
      </div>

      <div class="swiper-pagination"></div>
    </div>

    <div class="onboarding-next">
      <div class="pagination"></div>
      <a href="javascript:;" id="btn-onboarding" class="btn btn-white">Continue</a>
    </div>

  </section>
</div>

<div class="container d-flex flex-column">

  <section class="choices" id="choices">
    <h2 class="text-center">What do you want to do?</h2>

    <div class="choice-item">
      <%= image_tag "browse-items.svg", class: "choice-img" %>
      <a href="javascript:;"  id="btn-browse" >
        <div class="big-button">
          <small>Browse all items</small>
          <%= image_tag "arrow.svg", class: "icon" %>
        </div>
      </a>
    </div>
    <div class="choice-item">
      <%= image_tag"create-store-room.svg", class: "choice-img" %>
      <%= link_to new_storage_path do %>
        <div class="big-button">
          <small style="max-width:150px">Create your storage room</small>
          <%= image_tag "arrow.svg", class: "icon" %>
        </div>
      <% end  %>
      </a>
    </div>
  </section>

  <section class="browse" id="browse">
    <h2 class="text-center mb-4">What are you looking for ?</h2>
    <p class="text-center mt-5">Look here for a specific item</p>
    <%= render 'shared/search_bar' %>

    <p class="text-center mt-5 mb-2">Select here the activity's category that you would like to do.</p>
    <div class="grid">
      <% @categories.each do |category| %>
        <%= link_to category_path(category) do %>
          <div class="button-link-white">
            <small><%= category.name %></small>
            <%= cl_image_tag category.photo.key %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>

</div>

app/views/pages/search.html.erb
<div class="container">

  <h2><% if params[:query] %>Here are the results!<% else %>Looking for something ?<% end %></h2>
  <div class="map-container">
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <p class="mt-4"><strong><% if @storage_items != nil %><%= @storage_items.length %></strong> items found.<% end %></p>
  <% if params[:query].present? || params[:search_array].present? %>
  <% @belongings.each do |belonging| %>
    <div class="d-flex justify-content-between align-items-center item-card-user">
      <div class="d-flex justfiy-content-between align-items-center user-items-div">
        <%= link_to user_path(belonging[0]) do %>
        <div class="d-flex align-items-center pl-2 mr-3 user-name-img">
          <%= cl_image_tag belonging[0].photo.key, class: "icon-user" %>
        <p class="m-0"><%= belonging[0].username %></p>
        </div>
        <div class="user-items-icons">
          <% belonging[1].each do |item| %>
            <%= cl_image_tag item.item.photo.key, class: "icon-item-small" %>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="js-fly" data-lat="<%= belonging[0].storage.latitude %>" data-lng="<%= belonging[0].storage.longitude %>">
        <%= image_tag "pin-map.png", class: "map-marked" %></div>
      </div>
      <% end %>
  <% end %>

  <div class="form-container">
      <%= form_tag search_path, method: :get do %>
      <div id="search-data" data-items="<%=@items%>">
        <p>Looking for something else ?<p>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        placeholder: "Search here" %>
        <%= submit_tag "Search", class: "btn btn-white" %>
      </div>
      <% end %>
  </div>
</div>