config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    resources :users, only: %i[show edit]
    get '/users/:id/chatrooms', to: 'users#chatrooms', as: :user_chatrooms
  end

  root to: 'pages#home'

  get '/search', to: 'pages#search'
  get '/dashboard', to: 'pages#dashboard'

  resources :categories, only: %i[new create index show]
  resources :activities, only: %i[new create show]
  resources :storages, only: %i[show new create edit update]
  resources :items, only: %i[index new create]
  resources :item_storages, only: %i[new create edit update destroy]
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: :create
  end
end

app/models/item.rb
class Item < ApplicationRecord
  # attach cloudinary picture
  has_one_attached :photo

  # define databse relationships
  has_many :activity_items
  has_many :activities, through: :activity_items
  has_many :item_storages
  has_many :storages, through: :item_storages
  has_many :item_materials
  has_many :materials, through: :item_materials

  # define search tool for name field
  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: [:name],
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }

  # calculates the volume of an item
  def space_taken
    return ((height * width * length ))
  end

  # calculates the carbon footprint of an item
  def carbon_footprint_calc
    carbon = 0
    self.item_materials.each do |m|
      carbon += ((weight * m.percentage_weight) * m.material.co2_per_kilo).round(2)
    end
    self.carbon_footprint = carbon.round(3)
    self.save!
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  after_action :verify_authorized, only: [:new, :create, :edit, :destroy]

  def index
    # if params[:query].present?
    # end
    # else
    #   @items = ItemStorage.all
    # end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    authorite @item
    item_params.activity_ids.each do |id|
      ActivityItem.create(activity_id: id, item: @item)
    end
    if @item.save!
      redirect_to root_path # needs to change to desired path
    else
      render :new
    end
  end



  private

  def item_params
    params.require(:item).permit(:name, :photo, :weight, :height, :width, :length,:carbon_footprint, activity_ids: [])
  end
end

app/views/items/index.html.erb
  <%= form_tag items_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
  placeholder: "Search for item to borrow" %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

  <% @items.each do |item| %>
  <%= item.item.name %>
  <%= item.storage.address %>
  <% end %>

  <% if policy(:item).new?  %>
  <p><%= button_to "Add new item", new_item_path, method: :get %></p>
  <% end %>

app/views/items/new.html.erb
<div class="container">
  <h2>Add a new item</h2>
  <%= simple_form_for(@item) do |f| %>
    <%= f.input :name %>
    <%= f.association :activities %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-new"%>
  <% end %>
</div>