config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    resources :users, only: %i[show edit]
    get '/users/:id/chatrooms', to: 'users#chatrooms', as: :user_chatrooms
  end

  root to: 'pages#home'

  get '/search', to: 'pages#search'
  get '/dashboard', to: 'pages#dashboard'

  resources :categories, only: %i[new create index show]
  resources :activities, only: %i[new create show]
  resources :storages, only: %i[show new create edit update]
  resources :items, only: %i[index new create]
  resources :item_storages, only: %i[new create edit update destroy]
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: :create
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # attach cloudinary picture
  has_one_attached :photo

  # define databse relationships
  has_many :activities
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # after_action :verify_authorized, except: [:index, :show]
  # after_action :verify_policy_scoped, only: [:index, :show]
 before_action :authenticate_user! , except: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path # needs to change to desired path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/index.html.erb
<div class="container">
  <h2>Pick a category</h2>
  <div class="grid mt-4">
      <% @categories.each do |category| %>
        <%= link_to category_path(category) do %>
          <div class="big-button">
            <small><%= category.name %></small>
            <%= cl_image_tag category.photo.key %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= simple_form_for @category do |f| %>
      <div class="form">
        <div class="form-info">
          <%= f.input :name, label: 'Your category name:', required: true %>
        </div>

        <div class="form-info">
          <%= f.input :photo, as: :file, required: true %>
        </div>
      </div>
      <%= f.button :submit, "Create your category", class: "primary-button"  %>

    <% end %>

app/views/categories/show.html.erb
<div class="container">
  <div class="show-container">
    <div class="d-flex justify-content-between align-items-center mt-3">
      <h2><%= @category.name %></h2>
      <div class="category-icon"><%= cl_image_tag @category.photo.key %></div>
    </div>

    <div class="grid list-container">
      <% @category.activities.each do |activity| %>
        <%= link_to activity_path(activity) do %>
        <div class="btn button-link-white">
          <small><%= activity.name %></small>
          <%= image_tag "arrow.svg", class: "icon"  %>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="list-container">
       <%= link_to categories_path do %>
        <div class="btn btn-list-white">
          <%= image_tag "arrow-white.svg", class: "back"%>
          <small>Back to categories</small>
      </div>
      <% end %>
    </div>

  </div>
</div>